import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-6 m-10 justify-center">
          <Link href="/">Add Post</Link>
          <Link href="/posts">List Posts</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
